  /**
  
  CRIACAO DA TABELA DE CAMPANHA, TIME E CLIENTE
  
  DATA DE CRIAÇÃO: 12/07/17

**/ 
CREATE TABLE TIME (
    COD_TIME NUMBER,
    NOM_TIME VARCHAR2(200),
	DAT_CADASTRO DATE,
    CONSTRAINT PK_TIME PRIMARY KEY (COD_TIME)
) TABLESPACE CAPCIELO_D;

GRANT INSERT, UPDATE, SELECT ON TIME TO CAPRW;
CREATE SYNONYM CAPRW.TIME FOR TIME;

CREATE SEQUENCE SEQ_COD_TIME
START WITH 1 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;


CREATE TABLE CAMPANHA (
    COD_CAMPANHA NUMBER,
    NOM_CAMPANHA VARCHAR2(200),
	COD_TIME NUMBER,
	DAT_INICIO DATE,
	DAT_FIM DATE,
    CONSTRAINT PK_CAMPANHA PRIMARY KEY (COD_CAMPANHA),
	CONSTRAINT FK_CAMPANHA_TIME FOREIGN KEY (COD_TIME) REFERENCES TIME(COD_TIME)
) TABLESPACE CAPCIELO_D;

GRANT INSERT, UPDATE, SELECT ON CAMPANHA TO CAPRW;
CREATE SYNONYM CAPRW.CAMPANHA FOR CAMPANHA;

CREATE SEQUENCE SEQ_COD_CAMPANHA
START WITH 1 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;


CREATE TABLE CLIENTE (
    COD_CLIENTE NUMBER,
    NOM_CLIENTE VARCHAR2(200),
	EMAIL VARCHAR2(200),
	DAT_NASCIMENTO DATE,
	COD_TIME NUMBER,
	FLAG_ATIVO VARCHAR2(1),
	DAT_CADASTRO DATE,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE),
	CONSTRAINT FK_CLIENTE_TIME FOREIGN KEY (COD_TIME) REFERENCES TIME(COD_TIME)
) TABLESPACE CAPCIELO_D;

GRANT INSERT, UPDATE, SELECT ON CLIENTE TO CAPRW;
CREATE SYNONYM CAPRW.CLIENTE FOR CLIENTE;

CREATE SEQUENCE SEQ_COD_CLIENTE
START WITH 1 INCREMENT BY 1 CACHE 20 NOORDER NOCYCLE;

